<?php
/**
 * CDREntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-03-27T11:07:47Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CDREntryTest Class Doc Comment
 *
 * @category    Class */
// * @description CDREntry
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CDREntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CDREntry"
     */
    public function testCDREntry()
    {

    }

    /**
     * Test attribute "record_name"
     */
    public function testPropertyRecordName()
    {

    }

    /**
     * Test attribute "queue_name"
     */
    public function testPropertyQueueName()
    {

    }

    /**
     * Test attribute "trunk_name"
     */
    public function testPropertyTrunkName()
    {

    }

    /**
     * Test attribute "unique_id"
     */
    public function testPropertyUniqueId()
    {

    }

    /**
     * Test attribute "instance_id"
     */
    public function testPropertyInstanceId()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "extension_src"
     */
    public function testPropertyExtensionSrc()
    {

    }

    /**
     * Test attribute "extension_dst"
     */
    public function testPropertyExtensionDst()
    {

    }

    /**
     * Test attribute "ani"
     */
    public function testPropertyAni()
    {

    }

    /**
     * Test attribute "dnis"
     */
    public function testPropertyDnis()
    {

    }

    /**
     * Test attribute "clid"
     */
    public function testPropertyClid()
    {

    }

    /**
     * Test attribute "answer_time"
     */
    public function testPropertyAnswerTime()
    {

    }

    /**
     * Test attribute "dial_time"
     */
    public function testPropertyDialTime()
    {

    }

    /**
     * Test attribute "date_created_str"
     */
    public function testPropertyDateCreatedStr()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "date_indexed_str"
     */
    public function testPropertyDateIndexedStr()
    {

    }

    /**
     * Test attribute "date_indexed"
     */
    public function testPropertyDateIndexed()
    {

    }

}
