<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-03-27T11:07:47Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for aclDelete
     *
     * .
     *
     */
    public function testAclDelete()
    {

    }

    /**
     * Test case for aclGet
     *
     * .
     *
     */
    public function testAclGet()
    {

    }

    /**
     * Test case for aclOptions
     *
     * .
     *
     */
    public function testAclOptions()
    {

    }

    /**
     * Test case for aclPatch
     *
     * .
     *
     */
    public function testAclPatch()
    {

    }

    /**
     * Test case for blacklistIdDelete
     *
     * .
     *
     */
    public function testBlacklistIdDelete()
    {

    }

    /**
     * Test case for blacklistIdOptions
     *
     * .
     *
     */
    public function testBlacklistIdOptions()
    {

    }

    /**
     * Test case for blacklistIdPut
     *
     * .
     *
     */
    public function testBlacklistIdPut()
    {

    }

    /**
     * Test case for cdrGet
     *
     * .
     *
     */
    public function testCdrGet()
    {

    }

    /**
     * Test case for cdrOptions
     *
     * .
     *
     */
    public function testCdrOptions()
    {

    }

    /**
     * Test case for didsGet
     *
     * .
     *
     */
    public function testDidsGet()
    {

    }

    /**
     * Test case for didsIdOptions
     *
     * .
     *
     */
    public function testDidsIdOptions()
    {

    }

    /**
     * Test case for didsIdPatch
     *
     * .
     *
     */
    public function testDidsIdPatch()
    {

    }

    /**
     * Test case for didsOptions
     *
     * .
     *
     */
    public function testDidsOptions()
    {

    }

    /**
     * Test case for extensionsGet
     *
     * .
     *
     */
    public function testExtensionsGet()
    {

    }

    /**
     * Test case for extensionsIdOptions
     *
     * .
     *
     */
    public function testExtensionsIdOptions()
    {

    }

    /**
     * Test case for extensionsIdPatch
     *
     * .
     *
     */
    public function testExtensionsIdPatch()
    {

    }

    /**
     * Test case for extensionsOptions
     *
     * .
     *
     */
    public function testExtensionsOptions()
    {

    }

    /**
     * Test case for loginOptions
     *
     * .
     *
     */
    public function testLoginOptions()
    {

    }

    /**
     * Test case for loginPost
     *
     * .
     *
     */
    public function testLoginPost()
    {

    }

    /**
     * Test case for meGet
     *
     * .
     *
     */
    public function testMeGet()
    {

    }

    /**
     * Test case for meOptions
     *
     * .
     *
     */
    public function testMeOptions()
    {

    }

    /**
     * Test case for queuesGet
     *
     * .
     *
     */
    public function testQueuesGet()
    {

    }

    /**
     * Test case for queuesIdOptions
     *
     * .
     *
     */
    public function testQueuesIdOptions()
    {

    }

    /**
     * Test case for queuesIdPatch
     *
     * .
     *
     */
    public function testQueuesIdPatch()
    {

    }

    /**
     * Test case for queuesOptions
     *
     * .
     *
     */
    public function testQueuesOptions()
    {

    }

    /**
     * Test case for queuesPost
     *
     * .
     *
     */
    public function testQueuesPost()
    {

    }

    /**
     * Test case for versionGet
     *
     * .
     *
     */
    public function testVersionGet()
    {

    }

    /**
     * Test case for versionOptions
     *
     * .
     *
     */
    public function testVersionOptions()
    {

    }

}
